name: Build CI
description: A template for building project
inputs:
  repo: # name of repo
    description: The name of the repo to build
    default: ''
    required: true
  token: # github token
    description: The github token to use
    default: ''
    required: true
  REGISTRY:
    description: The registry to use
    default: ghcr.io
    required: true
  BASE_IMG_NAME:
    description: The base image name to use
    default: ${{ github.repository }}
    required: true
runs:
  using: composite
  steps:
  - name: Check out the repo
    uses: actions/checkout@v3
  - name: Log in to registry
    uses: docker/login-action@v2 
    with:
      registry: ${{ inputs.REGISTRY }}
      username: ${{ github.actor }}
      password: ${{ inputs.token }}
  - name: Derive short SHA name
    id: vars
    run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    shell: bash
  - name: Build image
    run: |
      docker build . --file Dockerfile --no-cache \
      --tag ghcr.io/${{ inputs.BASE_IMG_NAME }}/${{ inputs.repo }}:${{ steps.vars.outputs.sha_short }} \
      --tag ghcr.io/${{ inputs.BASE_IMG_NAME }}/${{ inputs.repo }}:latest
    shell: bash
  - name: Publish the image
    run: |
      docker push ghcr.io/${{ inputs.BASE_IMG_NAME }}/${{ inputs.repo }}:${{ steps.vars.outputs.sha_short }}
      docker push ghcr.io/${{ inputs.BASE_IMG_NAME }}/${{ inputs.repo }}:latest
    shell: bash