name: Build CI
description: A template for building project
inputs:
  repo: # name of repo
    description: The name of the repo to build
    default: ''
    required: true
runs:
  using: composite
  steps:
  - name: Check out the repo
    uses: actions/checkout@v3
  - name: Log in to registry
    uses: docker/login-action@v2 
    with:
      registry: ${{ env.REGISTRY }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
  - name: Derive short SHA name
    id: vars
    run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    shell: bash
  - name: Build image
    run: |
      docker build . --file Dockerfile --no-cache \
      --tag ghcr.io/${{ env.BASE_IMG_NAME }}/${{ inputs.repo }}:${{ steps.vars.outputs.sha_short }} \
      --tag ghcr.io/${{ env.BASE_IMG_NAME }}/${{ inputs.repo }}:latest
    shell: bash
  - name: Publish the image
    run: |
      docker push ghcr.io/${{ env.BASE_IMG_NAME }}/${{ inputs.repo }}:${{ steps.vars.outputs.sha_short }}
      docker push ghcr.io/${{ env.BASE_IMG_NAME }}/${{ inputs.repo }}:latest
    shell: bash

  
# on:
#   push:
#     branches: [ master ]

# env:
#   REGISTRY: ghcr.io
#   BASE_IMG_NAME: ${{ github.repository }}

# jobs:
#   build-as-seating:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#     - name: Check out the repo
#       uses: actions/checkout@v3
#     - name: Log in to registry
#       uses: docker/login-action@v2 
#       with:
#         registry: ${{ env.REGISTRY }}
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#     - name: Derive short SHA name
#       id: vars
#       run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
#     - name: Build image
#       run: |
#         docker build . --file Dockerfile --no-cache \
#         --tag ghcr.io/${{ env.BASE_IMG_NAME }}/as-seating:${{ steps.vars.outputs.sha_short }} \
#         --tag ghcr.io/${{ env.BASE_IMG_NAME }}/as-seating:latest
#     - name: Publish the image
#       run: |
#         docker push ghcr.io/${{ env.BASE_IMG_NAME }}/as-seating:${{ steps.vars.outputs.sha_short }}
#         docker push ghcr.io/${{ env.BASE_IMG_NAME }}/as-seating:latest